version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress1
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: wordpress1
      MYSQL_PASSWORD: wordpress1

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: wordpress1
      WORDPRESS_DB_NAME: wordpress1
volumes:
  db_data: {}
