version: "3.3"

services:
  database:
    image: mysql:5.7
    container_name: ${DOMAIN_NAME}_db
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DOMAIN_NAME}
      MYSQL_DATABASE: wp_${DOMAIN_NAME}
      MYSQL_USER: wp_${DOMAIN_NAME}
      MYSQL_PASSWORD: ${DOMAIN_NAME}

  phpmyadmin:
    image: phpmyadmin
    container_name: ${DOMAIN_NAME}_pma
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${DOMAIN_NAME}_db
      MYSQL_ROOT_PASSWORD: ${DOMAIN_NAME}

  wordpress:
    image: wordpress:latest
    container_name: ${DOMAIN_NAME}
    depends_on:
      - database
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "${WP_PORT}:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${DOMAIN_NAME}_db:3306
      WORDPRESS_DB_NAME: wp_${DOMAIN_NAME}
      WORDPRESS_DB_USER: wp_${DOMAIN_NAME}
      WORDPRESS_DB_PASSWORD: ${DOMAIN_NAME}
