services:
  wordpress:
    image: wordpress:latest
    container_name: ${DOMAIN_NAME}_wp
    volumes:
      - ./wordpress:/var/www/html
      - ../../nginx-proxy-manager/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "${WP_PORT}:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: dc_db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - network

networks:
  network:
    name: nginx_network
    external: true
