services:
  nginx:
    # image: "jc21/nginx-proxy-manager:latest"
    image: nginx:latest
    container_name: wp_nginx
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port |
    # Email: admin@example.com
    # Password: changeme

    # Add any other Stream port you want to expose
    # - '21:21' # FTP

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./logrotate.d/nginx-proxy-manager:/etc/logrotate.d/nginx-proxy-manager
      - ./certbot/www/:/var/www/certbot/:ro
      - ./conf.d/:/etc/nginx/conf.d:ro
    networks:
      - network

  certbot:
    image: certbot/certbot:latest
    container_name: wp_certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: /bin/sh -c 'sleep infinity'

  php:
    container_name: wp_php
    build: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - network

  wp_db:
    # image: mysql:5.7
    image: mariadb
    container_name: wp_db
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin
    container_name: wp_pma
    depends_on:
      - wp_db
    restart: unless-stopped
    ports:
      - "9005:80"
    environment:
      PMA_HOST: wp_db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 300M
    networks:
      - network

networks:
  network:
    name: wp_nginx_network
    driver: bridge
