version: "3"

services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: docker_container_nginx
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port |
    # Email: admin@example.com
    # Password: changeme

    # Add any other Stream port you want to expose
    # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
    # Uncomment this if you want to change the location of
    #   the SQLite DB file within the container
    # DB_SQLITE_FILE: "/data/database.sqlite"

    # Uncomment this if IPv6 is not enabled on your host
    # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    # networks:
    #   - network

  php:
    container_name: docker_container_php
    build: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    # networks:
    #   - network
# networks:
#   network:
#     name: docker_container_network
#     driver: bridge
